GssapiSessionModule DEFINITIONS ::= BEGIN

    Uint32 ::= INTEGER (0..4294967295)

    GSSSessionData ::= SEQUENCE {
        expiration  [0] Uint32,
        username    [1] OCTET STRING,
        gssname     [2] OCTET STRING
    }
END
